# Generated by Django 5.2.16 on 2026-08-06 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_serviceprovider_email_serviceprovider_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='postal_code',
            field=models.CharField(help_text='6-digit PIN code', max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must be 6 digits', regex='^[0-9]{6}$')]),
        ),
    ]
