# Generated by Django 5.2.16 on 2026-08-06 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_latitude_alter_client_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(help_text="Client's PIN code", max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must be exactly 6 digits', regex='^\\d{6}$')]),
        ),
    ]
