# Generated by Django 5.2.16 on 2026-08-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Source IP address of the failed login attempts')),
                ('city', models.CharField(blank=True, default='', help_text='Approximate city resolved via IP geolocation (filled asynchronously)', max_length=100)),
                ('attempted_username', models.CharField(blank=True, default='', help_text='Email address or username used in the login attempt', max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the security event was created')),
                ('user_agent', models.TextField(blank=True, default='', help_text='HTTP User-Agent header from the request')),
                ('failed_attempt_count', models.PositiveSmallIntegerField(help_text='Number of consecutive failed attempts at the time of this event')),
                ('is_resolved', models.BooleanField(default=False, help_text='Admin can mark the event as reviewed / resolved')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether the admin alert email was successfully sent')),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
