# Generated by Django 5.2.16 on 2026-08-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityevent',
            name='city',
        ),
    ]
